# Generated by Django 5.2.17 on 2026-09-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('category', models.CharField(choices=[('costume', 'Costume'), ('prop', 'Prop'), ('set_piece', 'Set piece')], default='costume', max_length=20)),
                ('size_label', models.CharField(blank=True, max_length=20)),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Worn'), (3, 'Good'), (4, 'Very good'), (5, 'Like new')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.bin')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
